spring:
   datasource:
      username: hot_springs
      password: hot_springs
      url: jdbc:mysql://localhost:3306/hot_springs
      
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
      defer-datasource-initialization: true
      
   sql:
      init:
         mode: never
   